/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xwr_speex_SpeexUtil */

#ifndef _Included_com_xwr_speex_SpeexUtil
#define _Included_com_xwr_speex_SpeexUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xwr_speex_SpeexUtil_DEFAULT_COMPRESSION
#define com_xwr_speex_SpeexUtil_DEFAULT_COMPRESSION 8L
/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xwr_speex_SpeexUtil_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xwr_speex_SpeexUtil_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_xwr_speex_SpeexUtil_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_xwr_speex_SpeexUtil_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xwr_speex_SpeexUtil_close
  (JNIEnv *, jobject);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    initEcho
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_xwr_speex_SpeexUtil_initEcho
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    echoCancellation
 * Signature: ([S[S[S)V
 */
JNIEXPORT void JNICALL Java_com_xwr_speex_SpeexUtil_echoCancellation
  (JNIEnv *, jobject, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    echoCancellationEncode
 * Signature: ([S[S[B)I
 */
JNIEXPORT jint JNICALL Java_com_xwr_speex_SpeexUtil_echoCancellationEncode
  (JNIEnv *, jobject, jshortArray, jshortArray, jbyteArray);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    destroyEcho
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xwr_speex_SpeexUtil_destroyEcho
  (JNIEnv *, jobject);

/*
 * Class:     com_xwr_speex_SpeexUtil
 * Method:    getAecStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xwr_speex_SpeexUtil_getAecStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
